version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: wisdom-pow-server
    ports:
      - "8080:8080"
    env_file:
      - .env.server
    restart: unless-stopped
    networks:
      - wisdom-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: wisdom-pow-client
    depends_on:
      - server
    env_file:
      - .env.client
    restart: on-failure
    networks:
      - wisdom-network

networks:
  wisdom-network:
    driver: bridge 