name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Build
      run: make build

    - name: Build Docker images
      run: |
        docker build -t wisdom-pow-server:latest -f Dockerfile.server .

    - name: Test
      run: make test

    - name: Lint
      run: |
        make install-lint
        make lint 